package peanuttlexicalanalyzer;

public enum PeanuttToken {

    IGUAL, SOMA, MULT, MENOS, DIV, ID, INT, NAME, VALUE, LINE, COLUMN, IF, ELSE,
    SWITCH, ENDIF, THEN, WHILE, FOR, ENDFOR, INTEIRO, PALAVRA_RESERVADA, CARACTER,
    SIMBOLO, COMENTARIO, ERROR, REAL, STRING, MODULO, SINGLEQUOTE, DOUBLEQUOTE, CITATION,
    DIFF, LESSTHEN, LESSTHENEQUALS, GREATERTHEN, GREATERTHENEQUALS, BOOLEAN;

}
